<a href="https://colab.research.google.com/github/Namesakenberg/BrickByBrickML/blob/main/data_preprocessing_flats.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.set_option('display.max_rows',None)     # avoid truncating rows and columns
pd.set_option('display.max_columns',None)

In [3]:
df = pd.read_csv('/content/flats-flats.csv')

In [4]:
df.head()

,property_name,link,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,2 BHK Flat in Krishna Colony,https://www.99acres.com/2-bhk-bedroom-apartmen...,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ...",C68850746
1,2 BHK Flat in Ashok Vihar,https://www.99acres.com/2-bhk-bedroom-apartmen...,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ...",H68850564
2,2 BHK Flat in Sohna,https://www.99acres.com/2-bhk-bedroom-apartmen...,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ...",J68850120
3,2 BHK Flat in Sector 61 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Smart World Orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN,S68849476
4,2 BHK Flat in Sector 92 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Parkwood Westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ...",L47956793

In [5]:
df.shape

(3008, 20)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3008 entries, 0 to 3007
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3008 non-null   object
 1   link             3008 non-null   object
 2   society          3007 non-null   object
 3   price            3007 non-null   object
 4   area             2996 non-null   object
 5   areaWithType     3008 non-null   object
 6   bedRoom          3008 non-null   object
 7   bathroom         3008 non-null   object
 8   balcony          3008 non-null   object
 9   additionalRoom   1694 non-null   object
 10  address          3002 non-null   object
 11  floorNum         3006 non-null   object
 12  facing           2127 non-null   object
 13  agePossession    3007 non-null   object
 14  nearbyLocations  2913 non-null   object
 15  description      3008 non-null   object
 16  furnishDetails   2203 non-null   object
 17  features         2594 non-null   object
 18  rating           2676 non-null   object
 19  property_id      3008 non-null   object
dtypes: object(20)
memory usage: 470.1+ KB

In [7]:
print(df.duplicated().sum())

0

In [8]:
print(df.isnull().sum())

property_name         0
link                  0
society               1
price                 1
area                 12
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom     1314
address               6
floorNum              2
facing              881
agePossession         1
nearbyLocations      95
description           0
furnishDetails      805
features            414
rating              332
property_id           0
dtype: int64

In [9]:
# removing links and property_id since they are not important
df.drop(columns = ['link','property_id'],inplace = True)

In [10]:
# rename the "area" column as "price per sqft"
df.rename(columns={'area':'price_per_sqft'},inplace = True)

In [11]:
# society is a categorical variable

print(df['society'].value_counts())

society
SS The Leaf3.8 ★                                     73
Tulip Violet4.3 ★                                    40
Shapoorji Pallonji Joyville Gurugram4.0 ★            39
Signature Global Park4.0 ★                           36
Shree Vardhman Victoria3.8 ★                         35
Tulip Violet4.2 ★                                    33
Smart World Gems                                     32
Emaar MGF Emerald Floors Premier3.8 ★                32
Smart World Orchard                                  32
DLF The Ultima4.0 ★                                  31
Paras Dews                                           31
DLF Regal Gardens3.9 ★                               30
Shree Vardhman Flora3.8 ★                            29
M3M Woodshire4.0 ★                                   29
La Vida by Tata Housing                              28
Godrej Nature Plus                                   27
Signature Global Solera3.7 ★                         27
BPTP Terra3.8 ★                                      25
Emaar Gurgaon Greens4.1 ★                            25
Eldeco Accolade3.8 ★                                 24
DLF New Town Heights 13.9 ★                          24
Vatika Gurgaon 213.7 ★                               24
Experion The Heartsong3.9 ★                          24
Bestech Park View Residency3.9 ★                     23
Tata Primanti4.1 ★                                   22
Emaar Palm Gardens4.1 ★                              22
ATS Triumph3.9 ★                                     22
M3M Heights                                          22
Sare Crescent Parc3.5 ★                              21
ROF Ananda                                           21
Experion Windchants3.8 ★                             20
Godrej 1014.0 ★                                      20
Antriksh Heights3.7 ★                                19
Sare Homes                                           19
Mapsko Mount Ville4.1 ★                              18
Ambience Creacions                                   18
Indiabulls Centrum Park3.7 ★                         18
CHD Avenue 713.6 ★                                   18
ATS Tourmaline3.9 ★                                  18
Supertech Araville                                   18
Sobha City                                           18
M3M Golfestate4.4 ★                                  17
Godrej Summit3.7 ★                                   17
GLS Arawali Homes3.8 ★                               17
Conscient Heritage Max4.3 ★                          17
M3M Skywalk                                          17
M3M Merlin3.7 ★                                      16
Pareena Coban Residences                             16
Bestech Park View Grand Spa4.3 ★                     16
HCBS Sports Ville3.6 ★                               16
Umang Monsoon Breeze                                 15
Ansal Heights 86                                     15
Godrej Oasis3.9 ★                                    15
Emaar MGF The Palm Drive4.1 ★                        15
Umang Winter Hills3.9 ★                              14
Imperia The Esfera                                   14
Ramsons Kshitij3.7 ★                                 14
DLF The Primus3.9 ★                                  14
Corona Optus3.9 ★                                    14
MVN Athens3.7 ★                                      14
Vatika The Seven Lamps3.8 ★                          14
Ireo Victory Valley4.1 ★                             14
The Close North4.0 ★                                 14
Orchid Petals4.1 ★                                   14
Indiabulls Enigma                                    14
Ireo Skyon4.0 ★                                      14
Bestech Park View Ananda4.2 ★                        13
Central Park Flower Valley                           13
Ireo The Corridors                                   13
Puri Emerald Bay3.7 ★                                13
Adani M2K Oyster Grande3.9 ★                         11
SBTL Caladium                                        11
Alpha Corp GurgaonOne 844.0 ★                        11
TARC Maceo3.8 ★                                      11
DLF The Skycourt4.2 ★                                11
Godrej Aria3.8 ★                                     11
Raheja Vedaanta3.6 ★                                 11
M3M Soulitude                                        11
DLF New Town Heights 24.0 ★                          10
Puri Diplomatic Greens4.0 ★                          10
Capital Residences 360                               10
Signature Global Synera3.4 ★                         10
Godrej Air                                           10
Breez Global Hill View                               10
ATS Kocoon                                           10
Pivotal Devaan                                       10
Zara Aavaas                                          10
Pyramid Urban Homes 2                                10
Ramprastha The Edge Towers3.5 ★                      10
Emaar MGF Palm Hills4.0 ★                            10
Breez Global Heights4.2 ★                            10
Vatika City4.1 ★                                      9
AIPL The Peaceful Homes3.9 ★                          9
ILD Greens4.1 ★                                       9
Parsvnath Green Ville3.9 ★                            9
Bestech Park View Sanskruti4.2 ★                      9
Microtek Greenburg3.8 ★                               9
Pareena Mi Casa                                       9
M3M Skycity                                           8
M3M Capital                                           8
ss                                                    8
Emaar Digihomes                                       8
Tulip Ivory3.5 ★                                      8
AVL 36 Gurgaon3.7 ★                                   8
Vatika Lifestyle Homes3.8 ★                           8
Orris Aster Court Premier                             8
The Lions CGHS                                        8
Birla Navya                                           8
GLS Avenue 51                                         8
Bestech Altura                                        8
Sare Green ParC Phase 3                               7
Signature Global Orchard Avenue3.6 ★                  7
Signature Global City                                 7
Sare Crescent Parc Royal Greens Phase 1               7
Vipul Lavanya3.9 ★                                    7
Orris Carnation Residency3.7 ★                        7
Trisara Our Homes 3                                   7
Signature Andour Heights3.8 ★                         7
Mapsko Casa Bella3.8 ★                                7
Ireo The Grand Arch4.0 ★                              7
Emaar Imperial Gardens3.8 ★                           7
Assotech Blith                                        7
AIPL Zen Residences                                   7
Ansal Housing Highland Park                           7
Hero Homes                                            6
Signature Global City 63A                             6
Pyramid Urban                                         6
Ashiana Mulberry                                      6
Parsvnath Exotica3.7 ★                                6
Signature Global Park 4                               6
HSIIDC Sidco Aravali                                  6
Suncity Vatsal Valley                                 6
M3M Sierra 68                                         6
Pioneer Araya3.8 ★                                    6
Bestech Park View City4.1 ★                           6
Supertech Hues                                        6
Mapsko Royale Ville3.7 ★                              6
DLF Regency Park 13.6 ★                               6
Bestech Park View Spa Next4.0 ★                       6
BPTP Astaire Gardens3.7 ★                             6
Shapoorji Pallonji Joyville Gurugram                  6
Kiran Residency                                       6
Sidhartha NCR One Phase 14.2 ★                        6
Signature The Roselia3.6 ★                            6
Godrej Habitat                                        5
Satya The Hermitage3.5 ★                              5
Central Park Resorts4.4 ★                             5
Signature Global City 81                              5
Ireo Uptown4.1 ★                                      5
DLF Park Place4.1 ★                                   5
Vatika Sovereign Park                                 5
Signature Global Grand IVA3.9 ★                       5
Emaar MGF Emerald Estate3.8 ★                         5
Signature Global City 92                              5
DLF Regency Park 24.0 ★                               5
Ashiana Anmol3.5 ★                                    5
Essel Towers                                          5
Apna Enclave                                          5
Greenopolis                                           5
Green Court3.7 ★                                      5
Krisumi Waterfall Residences                          5
Silverglades The Melia                                5
Pioneer Park3.8 ★                                     5
Pareena Laxmi Apartments3.6 ★                         5
Conscient Elevate                                     5
Signature Global the Millennia                        5
ATS Marigold                                          5
Signature Global City 37D Ph 2                        5
M3M The Marina4.0 ★                                   5
Vatika City Homes3.9 ★                                5
Central Park Flower Valley Aqua Front Towers          5
Adani Brahma Samsara Vilasa                           5
Raheja Navodaya3.6 ★                                  4
Ramprastha Skyz                                       4
Signature The Serenas                                 4
DLF The Skycourt                                      4
HSIIDC Sidco Shivalik Apartments3.8 ★                 4
Lotus Homz4.0 ★                                       4
Krrish Provence Estate                                4
SS The Coralwood3.4 ★                                 4
Ramprastha Primera                                    4
DLF New Town Heights3.7 ★                             4
Tata Gurgaon Gateway3.8 ★                             4
Prime Habitat                                         4
Godrej Frontier3.7 ★                                  4
Sare Petioles                                         4
Corona Gracieux                                       4
Unitech Fresco3.8 ★                                   4
Tulip Monsella                                        4
ILD Grand                                             4
Unitech Vistas                                        4
Emaar Palm Heights                                    4
Railway Officers RPF Society                          4
Global Hill View                                      4
Godrej Icon                                           4
Orris Aster Court                                     4
Sidhartha NCR Greens4.3 ★                             3
Tulip Petals3.6 ★                                     3
Piedmont Taksila heights3.6 ★                         3
Shri Ram Apartments                                   3
Krrish Florence Estate                                3
Valley View Estate                                    3
The Roselia 2                                         3
Essel Tower                                           3
Spaze Privy AT43.9 ★                                  3
Suncity Platinum Towers                               3
Dhoot Time Residency4.0 ★                             3
ATS Kocoon4.2 ★                                       3
Satya Element One                                     3
Vatika Xpressions                                     3
Puri Diplomatic Greens3.9 ★                           3
Sunischit Apartments                                  3
Smriti Apartment                                      3
DLF The Arbour                                        3
Apex Our Homes                                        3
Spaze Privvy The Address3.9 ★                         3
Sare Green Parc 2                                     3
SS Almeria                                            3
Sukhshanti Apartment                                  3
DLF The Grove                                         3
Unitech Sunbreeze                                     3
Tulip White3.5 ★                                      3
Sapphire Eighty Three                                 3
Guru Gram Haryana CGHS4.1 ★                           3
DLF Express Greens3.9 ★                               3
Shree Arihant Apartment                               3
Mahindra Aura4.2 ★                                    3
Shri Banke Bihari Society3.8 ★                        3
Adani Aangan Arcade                                   3
Siddhartha Apartment                                  3
Vatika Independent Floors3.8 ★                        3
Pivotal Riddhi Siddhi                                 3
DLF Carlton Estate4.0 ★                               3
Unitech Heritage City                                 3
Kendriya Vihar4.1 ★                                   3
Signature Global Solera 2                             3
AFNHB Jalvayu Vihar3.7 ★                              3
Bestech Park View City 23.9 ★                         3
Unitech The Residences3.7 ★                           3
Deepak Minda                                          3
Sare Green Parc                                       3
Chintels Paradiso3.9 ★                                3
Sidhartha NCR One                                     3
Raheja Sampada                                        3
DLF Belvedere Towers3.8 ★                             3
AIPL Club Residences                                  3
Paras Quartier                                        3
Ambience Lagoon3.9 ★                                  3
Whiteland Blissville                                  3
Pyramid Elite                                         3
Brisk Lumbini Terrace Homes                           3
Unitech Uniworld Gardens3.8 ★                         3
Raheja Revanta                                        3
Tulip Purple                                          3
Raheja Atharva3.6 ★                                   3
Maxworth City Residences                              3
Conscient Habitat3.6 ★                                3
Tulip Lemon3.9 ★                                      3
Spaze Privy3.9 ★                                      3
DLF Royalton Tower                                    3
Ambience Caitriona                                    2
Surendra Avenue 69                                    2
Ardee City3.8 ★                                       2
Jammu and Kashmir Bank Employees CGHS3.7 ★            2
Silverglades Hightown Residences                      2
Dlf City                                              2
Shapoorji Pallonji Joyville                           2
Breeze Global Heights                                 2
Element One Service                                   2
Milan CGHS 9                                          2
Vipul World Floors                                    2
Apartment                                             2
Bhagwati Sadan                                        2
Emaar MGF Palm Studios                                2
Vatika Emilia Floors3.7 ★                             2
Tulip Violet                                          2
Tulip Leaf                                            2
Viridian The Plaza 106                                2
CGHS Airport Apartment                                2
Ansal API Celebrity Suites                            2
M3M Latitude                                          2
BPTP Freedom Park Life4.0 ★                           2
Pioneer Urban Presidia                                2
Elan The Presidential                                 2
lagoon apartment                                      2
The Close South3.9 ★                                  2
Signature Global The Millennia 3                      2
Orchid Island4.2 ★                                    2
My Home                                               2
Puri The Aravallis                                    2
Raheja Atlantis3.8 ★                                  2
Ansal API Esencia3.7 ★                                2
AWHO Shanti Vihar4.0 ★                                2
ROF Aalayas3.8 ★                                      2
M3M Sky Lofts                                         2
Unitech Uniworld Gardens 23.4 ★                       2
Mahindra Luminare4.0 ★                                2
Bestech Spa Signature                                 2
SS Hibiscus                                           2
The Penthouses at the Hibiscus                        2
Tulip Orange3.9 ★                                     2
Central Park 2 Bellevue                               2
Landmark The Residency                                2
Vasant Appartments                                    2
Maruti Vihar                                          2
Housing Board Colony                                  2
BPTP Pedestal                                         2
MRG World Ultimus                                     2
Mapsko Paradise3.9 ★                                  2
Park Royal Apartment                                  2
HCBS Sports Ville                                     2
Adani Aangan Galleria                                 2
M3M Ikonic                                            2
Bestech Park View Sanskruti4.1 ★                      2
Green Campus CHS                                      2
Today Callidora                                       2
Ramprastha The Atrium3.4 ★                            2
Ramprastha City                                       2
Oriental Valley CHS                                   2
Aqua Front Towers                                     2
Sahara Grace                                          2
Professors Enclave CGHS                               2
DLF The Icon3.7 ★                                     2
DLF The Crest3.6 ★                                    2
Vipul Belmonte3.9 ★                                   2
Emaar MGF The Enclave                                 2
BPTP Amstoria3.8 ★                                    2
Suncity Avenue 1023.9 ★                               2
Suncity Heights3.7 ★                                  2
Ansal Heights3.2 ★                                    2
Ashiana Anmol                                         2
Godrej Nature Plus Serenity                           2
Suncity Avenue 76                                     2
Supertech Hill Town                                   2
NBCC Heights3.9 ★                                     2
M3M Urbana                                            2
Palam Vihar Society                                   2
Vatika INXT Floors                                    2
Raheja Vanya                                          2
Ganga Apartment                                       2
Lavanya Apartments                                    2
Supertech Hilltown                                    2
om appartments                                        2
Samaspurkunj                                          2
Residency Grand                                       2
Mittal Surya Vihar                                    2
Suposhaa Smartworld Orchard                           2
DLF The Belaire3.9 ★                                  2
Paras Irene3.7 ★                                      2
BPTP Mansions Park Prime                              2
Tulsiani Easy in Homes                                2
Sidhivinayak Apartments                               2
Spire Woods Now Ananda by Alpha corp                  1
maa bhagwati residency                                1
Parkwood Westend                                      1
Signature Global Infinity Mall                        1
The Cocoon                                            1

In [12]:
# some societies have rating in the name itself , thus it creates an additional category,thus handling the society name

In [13]:
df['society'].value_counts().shape  # total no. of categories = 636 , need to reduce it

(636,)

In [14]:
# keep only words in the name of the society
import re
df['society'] = df['society'].apply(lambda name:re.sub(r'\d+(\.\d+)?\s?★','',str(name)).strip()).str.lower()

In [15]:
df['society'].value_counts().shape

(602,)

In [16]:
# clean the price column

In [17]:
df[df['price']=='Price on Request'].shape[0]

# there are 11 rows where price is not specified , thus we remove such rows

df = df[df['price']!='Price on Request']

In [18]:
# the price column has 2 units lac and crore , making it a single unit "crore"

def price_conversion(x):
  if type(x)==float:
    return x
  else:
    if x[1] == 'Lac':
      return round(float(x[0])/100,2)
    else:
      return round(float(x[0]),2)
df['price']  = df['price'].str.split(' ').apply(price_conversion)

<ipython-input-18-267695690>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['price']  = df['price'].str.split(' ').apply(price_conversion)

## price /sq ft

In [19]:
# clean the price per sqft column by removing rupee sign , comma and the unit

def clean_price_per_sqft(x):
  x = str(x)
  cleaned = re.sub(r'[^\d.]', '', x)
  cleaned = re.sub(r'\.+$', '', cleaned)
  if cleaned=='':
    return 0.00
  return float(cleaned)
df['price_per_sqft'] = df['price_per_sqft'].apply(clean_price_per_sqft)

<ipython-input-19-1306992135>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['price_per_sqft'] = df['price_per_sqft'].apply(clean_price_per_sqft)

## Bedroom , Bathrooms and balcony

In [20]:
# handling bedrooms bathrooms and balcony

print(df['bedRoom'].isnull().sum())
print(df['bathroom'].isnull().sum())
print(df['balcony'].isnull().sum())

0
0
0

In [21]:
print(df['bedRoom'].value_counts())
print(df['bathroom'].value_counts())
print(df['balcony'].value_counts())

bedRoom
3 Bedrooms    1437
2 Bedrooms     944
4 Bedrooms     478
1 Bedroom      104
5 Bedrooms      31
6 Bedrooms       3
Name: count, dtype: int64
bathroom
2 Bathrooms    1044
3 Bathrooms     989
4 Bathrooms     636
5 Bathrooms     169
1 Bathroom      112
6 Bathrooms      42
7 Bathrooms       5
Name: count, dtype: int64
balcony
3 Balconies     974
3+ Balconies    862
2 Balconies     749
1 Balcony       315
No Balcony       97
Name: count, dtype: int64

In [22]:
def clean_bedroom(x):
  return int(x[0])
df['bedRoom'] = df['bedRoom'].apply(clean_bedroom)

def clean_bathroom(x):
  return int(x[0])
df['bathroom'] = df['bathroom'].apply(clean_bathroom)

df['balcony']=df['balcony'].str.split(' ').str.get(0).str.replace('No','0')

<ipython-input-22-2588129410>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['bedRoom'] = df['bedRoom'].apply(clean_bedroom)
<ipython-input-22-2588129410>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['bathroom'] = df['bathroom'].apply(clean_bathroom)
<ipython-input-22-2588129410>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['balcony']=df['balcony'].str.split(' ').str.get(0).str.replace('No','0')

## Extra Rooms

In [23]:
print(df['additionalRoom'].value_counts())

additionalRoom
Servant Room                                     629
Study Room                                       232
Others                                           179
Pooja Room                                       132
Study Room,Servant Room                           81
Store Room                                        76
Pooja Room,Servant Room                           60
Servant Room,Others                               52
Servant Room,Pooja Room                           30
Study Room,Others                                 27
Pooja Room,Study Room,Servant Room,Others         25
Pooja Room,Study Room,Servant Room                24
Servant Room,Store Room                           19
Pooja Room,Study Room                             13
Pooja Room,Study Room,Servant Room,Store Room     12
Servant Room,Study Room                            8
Study Room,Pooja Room                              8
Study Room,Servant Room,Store Room                 7
Pooja Room,Servant Room,Others                     6
Servant Room,Study Room,Pooja Room,Store Room      6
Pooja Room,Store Room                              6
Others,Servant Room                                6
Pooja Room,Others                                  6
Study Room,Servant Room,Others                     5
Pooja Room,Study Room,Store Room                   4
Pooja Room,Store Room,Study Room,Servant Room      4
Study Room,Pooja Room,Store Room                   3
Store Room,Servant Room                            3
Servant Room,Pooja Room,Study Room,Store Room      3
Servant Room,Others,Pooja Room                     2
Study Room,Servant Room,Pooja Room,Store Room      2
Servant Room,Study Room,Store Room                 2
Study Room,Pooja Room,Servant Room                 2
Servant Room,Others,Store Room,Pooja Room          2
Pooja Room,Study Room,Others                       2
Store Room,Pooja Room,Servant Room                 1
Pooja Room,Study Room,Store Room,Servant Room      1
Pooja Room,Servant Room,Study Room,Store Room      1
Servant Room,Pooja Room,Store Room                 1
Study Room,Servant Room,Store Room,Pooja Room      1
Study Room,Servant Room,Pooja Room                 1
Servant Room,Pooja Room,Store Room,Study Room      1
Study Room,Store Room                              1
Store Room,Study Room                              1
Servant Room,Pooja Room,Study Room                 1
Servant Room,Study Room,Pooja Room                 1
Others,Study Room                                  1
Servant Room,Study Room,Others                     1
Store Room,Pooja Room                              1
Name: count, dtype: int64

In [24]:
print(df['additionalRoom'].isnull().sum())

1305

In [25]:
# there are 1305 flats with no information given on additional room , thus fill the null values with not available

df['additionalRoom']= df['additionalRoom'].fillna('not available')

<ipython-input-25-3784659812>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['additionalRoom']= df['additionalRoom'].fillna('not available')

In [26]:
df['additionalRoom'] = df['additionalRoom'].str.lower()

<ipython-input-26-4218856625>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['additionalRoom'] = df['additionalRoom'].str.lower()

In [27]:
print(df['additionalRoom'].value_counts())

additionalRoom
not available                                    1305
servant room                                      629
study room                                        232
others                                            179
pooja room                                        132
study room,servant room                            81
store room                                         76
pooja room,servant room                            60
servant room,others                                52
servant room,pooja room                            30
study room,others                                  27
pooja room,study room,servant room,others          25
pooja room,study room,servant room                 24
servant room,store room                            19
pooja room,study room                              13
pooja room,study room,servant room,store room      12
servant room,study room                             8
study room,pooja room                               8
study room,servant room,store room                  7
pooja room,servant room,others                      6
servant room,study room,pooja room,store room       6
pooja room,store room                               6
others,servant room                                 6
pooja room,others                                   6
study room,servant room,others                      5
pooja room,study room,store room                    4
pooja room,store room,study room,servant room       4
study room,pooja room,store room                    3
store room,servant room                             3
servant room,pooja room,study room,store room       3
servant room,others,pooja room                      2
study room,servant room,pooja room,store room       2
servant room,study room,store room                  2
study room,pooja room,servant room                  2
servant room,others,store room,pooja room           2
pooja room,study room,others                        2
store room,pooja room,servant room                  1
pooja room,study room,store room,servant room       1
pooja room,servant room,study room,store room       1
servant room,pooja room,store room                  1
study room,servant room,store room,pooja room       1
study room,servant room,pooja room                  1
servant room,pooja room,store room,study room       1
study room,store room                               1
store room,study room                               1
servant room,pooja room,study room                  1
servant room,study room,pooja room                  1
others,study room                                   1
servant room,study room,others                      1
store room,pooja room                               1
Name: count, dtype: int64

## Floor num

In [28]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [29]:
print(df['floorNum'].isnull().sum())

2

In [30]:
print(df['floorNum'].value_counts())

floorNum
2nd   of 4 Floors           74
3rd   of 4 Floors           71
4th   of 4 Floors           62
1st   of 4 Floors           61
12nd   of 14 Floors         49
14th   of 14 Floors         48
Ground of 14 Floors         40
10th   of 14 Floors         35
7th   of 14 Floors          35
8th   of 14 Floors          34
4th   of 14 Floors          28
6th   of 14 Floors          27
2nd   of 2 Floors           26
1st   of 14 Floors          26
3rd   of 3 Floors           26
8th   of 19 Floors          24
5th   of 14 Floors          24
3rd   of 14 Floors          24
1st   of 1 Floors           23
9th   of 9 Floors           23
9th   of 14 Floors          23
11st   of 14 Floors         23
2nd   of 3 Floors           22
5th   of 12 Floors          22
2nd   of 14 Floors          21
8th   of 18 Floors          20
10th   of 19 Floors         18
6th   of 18 Floors          18
7th   of 15 Floors          17
Ground of 1 Floors          17
7th   of 18 Floors          17
10th   of 18 Floors         17
12nd   of 12 Floors         17
9th   of 13 Floors          17
5th   of 15 Floors          16
3rd   of 18 Floors          16
2nd   of 12 Floors          15
6th   of 12 Floors          15
9th   of 15 Floors          15
1st   of 3 Floors           15
6th   of 19 Floors          14
1st   of 2 Floors           13
10th   of 26 Floors         13
3rd   of 13 Floors          13
6th   of 10 Floors          13
5th   of 5 Floors           13
Ground of 4 Floors          13
7th   of 7 Floors           13
10th   of 10 Floors         12
6th   of 15 Floors          12
8th   of 12 Floors          11
16th   of 19 Floors         11
8th   of 8 Floors           11
9th   of 26 Floors          11
15th   of 19 Floors         11
11st   of 18 Floors         11
9th   of 24 Floors          11
17th   of 17 Floors         11
4th   of 10 Floors          11
6th   of 6 Floors           11
4th   of 13 Floors          11
4th   of 12 Floors          10
6th   of 13 Floors          10
3rd   of 5 Floors           10
7th   of 26 Floors          10
2nd   of 19 Floors          10
7th   of 13 Floors          10
1st   of 26 Floors          10
10th   of 12 Floors         10
7th   of 21 Floors          10
12nd   of 18 Floors         10
4th   of 15 Floors          10
3rd   of 9 Floors           10
15th   of 29 Floors          9
3rd   of 12 Floors           9
8th   of 22 Floors           9
18th   of 19 Floors          9
14th   of 19 Floors          9
9th   of 20 Floors           9
13rd   of 14 Floors          9
8th   of 15 Floors           9
7th   of 17 Floors           9
14th   of 15 Floors          9
12nd   of 17 Floors          9
5th   of 18 Floors           9
6th   of 26 Floors           9
7th   of 12 Floors           9
6th   of 16 Floors           9
3rd   of 15 Floors           8
9th   of 18 Floors           8
5th   of 13 Floors           8
3rd   of 19 Floors           8
1st   of 19 Floors           8
12nd   of 24 Floors          8
8th   of 24 Floors           8
9th   of 12 Floors           8
2nd   of 15 Floors           8
12nd   of 26 Floors          8
10th   of 13 Floors          8
8th   of 26 Floors           8
8th   of 13 Floors           8
12nd   of 19 Floors          8
10th   of 17 Floors          8
4th   of 26 Floors           8
2nd   of 5 Floors            8
2nd   of 8 Floors            8
5th   of 9 Floors            8
14th   of 24 Floors          8
2nd   of 10 Floors           7
13rd   of 13 Floors          7
8th   of 21 Floors           7
7th   of 19 Floors           7
12nd   of 15 Floors          7
9th   of 19 Floors           7
5th   of 29 Floors           7
11st   of 24 Floors          7
2nd   of 13 Floors           7
16th   of 16 Floors          7
8th   of 10 Floors           7
12nd   of 13 Floors          7
1st   of 13 Floors           7
4th   of 19 Floors           7
2nd   of 17 Floors           7
11st   of 11 Floors          7
5th   of 20 Floors           7
11st   of 13 Floors          7
10th   of 21 Floors          7
11st   of 26 Floors          7
5th   of 10 Floors           6
Ground of 15 Floors          6
4th   of 17 Floors           6
11st   of 12 Floors          6
7th   of 20 Floors           6
16th   of 18 Floors          6
5th   of 25 Floors           6
5th   of 22 Floors           6
14th   of 27 Floors          6
12nd   of 22 Floors          6
Ground of 16 Floors          6
17th   of 19 Floors          6
1st   of 10 Floors           6
2nd   of 20 Floors           6
10th   of 15 Floors          6
19th   of 19 Floors          6
15th   of 15 Floors          6
10th   of 20 Floors          6
3rd   of 25 Floors           6
11st   of 19 Floors          6
Ground of 3 Floors           6
6th   of 9 Floors            6
1st   of 5 Floors            6
10th   of 29 Floors          6
4th   of 18 Floors           6
9th   of 30 Floors           5
9th   of 11 Floors           5
12nd   of 21 Floors          5
14th   of 16 Floors          5
4th   of 27 Floors           5
Ground of 19 Floors          5
10th   of 24 Floors          5
Ground of 12 Floors          5
15th   of 21 Floors          5
1st   of 15 Floors           5
18th   of 29 Floors          5
10th   of 27 Floors          5
7th   of 8 Floors            5
15th   of 18 Floors          5
8th   of 9 Floors            5
6th   of 11 Floors           5
4th   of 9 Floors            5
11st   of 25 Floors          5
6th   of 20 Floors           5
16th   of 26 Floors          5
8th   of 30 Floors           5
10th   of 25 Floors          5
15th   of 28 Floors          5
12nd   of 29 Floors          5
1st   of 12 Floors           5
11st   of 16 Floors          5
11st   of 29 Floors          5
Ground of 21 Floors          5
7th   of 27 Floors           5
11st   of 30 Floors          5
14th   of 29 Floors          5
5th   of 19 Floors           5
1st   of 7 Floors            5
4th   of 22 Floors           5
6th   of 17 Floors           5
9th   of 22 Floors           5
3rd   of 20 Floors           5
5th   of 8 Floors            5
3rd   of 10 Floors           4
3rd   of 17 Floors           4
14th   of 21 Floors          4
3rd   of 22 Floors           4
7th   of 10 Floors           4
18th   of 32 Floors          4
15th   of 32 Floors          4
19th   of 40 Floors          4
11st   of 20 Floors          4
14th   of 18 Floors          4
23rd   of 26 Floors          4
11st   of 17 Floors          4
7th   of 11 Floors           4
13rd   of 19 Floors          4
17th   of 25 Floors          4
8th   of 16 Floors           4
20th   of 26 Floors          4
19th   of 24 Floors          4
13rd   of 21 Floors          4
Ground of 13 Floors          4
5th   of 24 Floors           4
8th   of 20 Floors           4
25th   of 25 Floors          4
17th   of 26 Floors          4
2nd   of 16 Floors           4
20th   of 20 Floors          4
2nd   of 11 Floors           4
11st   of 15 Floors          4
5th   of 16 Floors           4
2nd   of 9 Floors            4
17th   of 18 Floors          4
6th   of 30 Floors           4
5th   of 23 Floors           4
Ground of 17 Floors          4
3rd   of 11 Floors           4
22nd   of 30 Floors          4
22nd   of 24 Floors          4
14th   of 17 Floors          4
15th   of 23 Floors          4
1st   of 18 Floors           4
7th   of 9 Floors            4
17th   of 24 Floors          4
15th   of 16 Floors          4
14th   of 26 Floors          4
15th   of 25 Floors          4
12nd   of 16 Floors          4
4th   of 8 Floors            4
13rd   of 25 Floors          4
7th   of 24 Floors           4
15th   of 26 Floors          4
9th   of 10 Floors           4
12nd   of 30 Floors          4
6th   of 22 Floors           3
7th   of 23 Floors           3
8th   of 11 Floors           3
16th   of 20 Floors          3
26th   of 30 Floors          3
13rd   of 15 Floors          3
9th   of 16 Floors           3
10th   of 30 Floors          3
6th   of 24 Floors           3
1st   of 25 Floors           3
5th   of 30 Floors           3
12nd   of 27 Floors          3
18th   of 18 Floors          3
15th   of 40 Floors          3
15th   of 22 Floors          3
3rd   of 8 Floors            3
9th   of 40 Floors           3
31st   of 32 Floors          3
1st   of 11 Floors           3
3rd   of 26 Floors           3
6th   of 23 Floors           3
6th   of 29 Floors           3
18th   of 26 Floors          3
23rd   of 23 Floors          3
21st   of 22 Floors          3
4th   of 16 Floors           3
11st   of 27 Floors          3
2nd   of 22 Floors           3
10th   of 23 Floors          3
6th   of 21 Floors           3
14th   of 32 Floors          3
4th   of 21 Floors           3
21st   of 24 Floors          3
30th   of 32 Floors          3
24th   of 24 Floors          3
5th   of 17 Floors           3
19th   of 21 Floors          3
12nd   of 23 Floors          3
5th   of 26 Floors           3
20th   of 28 Floors          3
Ground of 26 Floors          3
15th   of 20 Floors          3
3rd   of 16 Floors           3
17th   of 30 Floors          3
10th   of 16 Floors          3
8th   of 17 Floors           3
2nd   of 26 Floors           3
9th   of 21 Floors           3
19th   of 29 Floors          3
Ground of 18 Floors          3
8th   of 25 Floors           3
15th   of 39 Floors          3
6th   of 8 Floors            3
8th   of 40 Floors           3
18th   of 30 Floors          3
1st   of 35 Floors           3
4th   of 29 Floors           3
17th   of 29 Floors          3
17th   of 20 Floors          3
4th   of 20 Floors           3
10th   of 28 Floors          3
19th   of 30 Floors          3
27th   of 27 Floors          3
1st   of 17 Floors           2
3rd   of 33 Floors           2
18th   of 21 Floors          2
14th   of 28 Floors          2
16th   of 32 Floors          2
16th   of 27 Floors          2
16th   of 24 Floors          2
2nd   of 6 Floors            2
19th   of 27 Floors          2
7th   of 30 Floors           2
13rd   of 30 Floors          2
10th   of 40 Floors          2
13rd   of 20 Floors          2
2nd   of 28 Floors           2
15th   of 31 Floors          2
27th   of 29 Floors          2
24th   of 30 Floors          2
Ground of 23 Floors          2
4th   of 11 Floors           2
9th   of 29 Floors           2
19th   of 20 Floors          2
2nd   of 24 Floors           2
14th   of 20 Floors          2
43   of 47 Floors            2
1st   of 22 Floors           2
16th   of 30 Floors          2
25th   of 29 Floors          2
23rd   of 29 Floors          2
20th   of 23 Floors          2
9th   of 17 Floors           2
11st   of 23 Floors          2
8th   of 23 Floors           2
8th   of 29 Floors           2
3rd   of 32 Floors           2
10th   of 32 Floors          2
2nd   of 7 Floors            2
4th   of 5 Floors            2
Ground of 51 Floors          2
28th   of 30 Floors          2
7th   of 16 Floors           2
17th   of 23 Floors          2
4th   of 7 Floors            2
15th   of 24 Floors          2
13rd   of 40 Floors          2
8th   of 34 Floors           2
25th   of 30 Floors          2
16th   of 21 Floors          2
7th   of 29 Floors           2
8th   of 32 Floors           2
6th   of 31 Floors           2
12nd   of 25 Floors          2
1st   of 24 Floors           2
39th   of 40 Floors          2
9th   of 28 Floors           2
16th   of 34 Floors          2
10th   of 22 Floors          2
7th   of 36 Floors           2
3rd   of 24 Floors           2
2nd   of 18 Floors           2
2nd   of 40 Floors           2
3rd   of 27 Floors           2
2nd   of 21 Floors           2
10th   of 11 Floors          2
2nd   of 25 Floors           2
1st   of 20 Floors           2
1st   of 30 Floors           2
22nd   of 25 Floors          2
1st   of 8 Floors            2
23rd   of 34 Floors          2
18th   of 24 Floors          2
Lower Ground of 4 Floors     2
4th   of 34 Floors           2
20th   of 25 Floors          2
7th   of 22 Floors           2
3rd   of 29 Floors           2
11st   of 21 Floors          2
8th   of 28 Floors           2
21st   of 27 Floors          2
2nd   of 32 Floors           2
15th   of 17 Floors          2
9th   of 27 Floors           2
20th   of 22 Floors          2
1st   of 16 Floors           2
16th   of 36 Floors          2
5th   of 11 Floors           2
40th   of 40 Floors          2
15th   of 45 Floors          2
17th   of 33 Floors          2
31st   of 40 Floors          1
18th   of 20 Floors          1
3rd   of 31 Floors           1
27th   of 30 Floors          1
34th   of 34 Floors          1
5th   of 36 Floors           1
18th   of 35 Floors          1
17th   of 31 Floors          1
21st   of 23 Floors          1
Ground of 5 Floors           1
Ground of 6 Floors           1
Basement of 13 Floors        1
18th   of 22 Floors          1
17th   of 22 Floors          1
24th   of 36 Floors          1
3rd   of 36 Floors           1
5th   of 6 Floors            1
8th   of 35 Floors           1
Lower Ground of 1 Floors     1
5th   of 35 Floors           1
Ground of 2 Floors           1
10th   of 33 Floors          1
13rd   of 47 Floors          1
34th   of 42 Floors          1
17th   of 21 Floors          1
4th   of 39 Floors           1
24th   of 32 Floors          1
20th   of 34 Floors          1
16th   of 22 Floors          1
18th   of 25 Floors          1
23rd   of 28 Floors          1
8th   of 27 Floors           1
28th   of 29 Floors          1
15th   of 27 Floors          1
11st   of 22 Floors          1
Ground of 11 Floors          1
20th   of 47 Floors          1
27th   of 48 Floors          1
6th   of 7 Floors            1
35th   of 51 Floors          1
22nd   of 28 Floors          1
11st   of 36 Floors          1
28th   of 28 Floors          1
Basement of 4 Floors         1
2nd   of 34 Floors           1
4th   of 40 Floors           1
3rd   of 40 Floors           1
20th   of 32 Floors          1
Basement of 28 Floors        1
19th   of 41 Floors          1
19th   of 26 Floors          1
2nd   of 27 Floors           1
14th   of 51 Floors          1
19th   of 39 Floors          1
12nd   of 39 Floors          1
38th   of 40 Floors          1
18th   of 40 Floors          1
6th   of 25 Floors           1
16th   of 25 Floors          1
4th   of 28 Floors           1
7th   of 32 Floors           1
30th   of 40 Floors          1
4th   of 25 Floors           1
19th   of 23 Floors          1
5th   of 27 Floors           1
24th   of 39 Floors          1
20th   of 30 Floors          1
18th   of 51 Floors          1
24th   of 27 Floors          1
19th   of 22 Floors          1
8th   of 31 Floors           1
33rd   of 48 Floors          1
35th   of 35 Floors          1
26th   of 47 Floors          1
Ground of 24 Floors          1
7th   of 25 Floors           1
20th   of 43 Floors          1
21st   of 51 Floors          1
12nd   of 28 Floors          1
10th   of 34 Floors          1
18th   of 23 Floors          1
12nd   of 32 Floors          1
23rd   of 40 Floors          1
5th   of 32 Floors           1
1st   of 9 Floors            1
3rd   of 6 Floors            1
20th   of 40 Floors          1
9th   of 42 Floors           1
10th   of 51 Floors          1
15th   of 30 Floors          1
21st   of 41 Floors          1
32nd   of 32 Floors          1
8th   of 42 Floors           1
26th   of 34 Floors          1
21st   of 29 Floors          1
20th   of 29 Floors          1
13rd   of 18 Floors          1
7th   of 34 Floors           1
10th   of 39 Floors          1
21st   of 26 Floors          1
1st   of 44 Floors           1
7th   of 42 Floors           1
25th   of 36 Floors          1
21st   of 28 Floors          1
14th   of 22 Floors          1
33rd   of 42 Floors          1
2nd   of 36 Floors           1
19th   of 31 Floors          1
16th   of 51 Floors          1
29th   of 31 Floors          1
22nd   of 40 Floors          1
16th   of 41 Floors          1
7th   of 40 Floors           1
12nd   of 40 Floors          1
3rd   of 28 Floors           1
17th   of 28 Floors          1
3rd   of 30 Floors           1
19th   of 32 Floors          1
16th   of 45 Floors          1
22nd   of 23 Floors          1
7th   of 28 Floors           1
21st   of 36 Floors          1
14th   of 41 Floors          1
Ground of 29 Floors          1
22nd   of 26 Floors          1
32nd   of 55 Floors          1
Ground of 40 Floors          1
13rd   of 22 Floors          1
16th   of 35 Floors          1
44   of 47 Floors            1
23rd   of 24 Floors          1
17th   of 47 Floors          1
4th   of 6 Floors            1
30th   of 34 Floors          1
24th   of 31 Floors          1
24th   of 51 Floors          1
29th   of 29 Floors          1
16th   of 31 Floors          1
5th   of 21 Floors           1
12nd   of 34 Floors          1
5th   of 34 Floors           1
9th   of 25 Floors           1
45   of 47 Floors            1
Ground of 25 Floors          1
9th   of 23 Floors           1
33rd   of 33 Floors          1
1st   of 6 Floors            1
20th   of 24 Floors          1
13rd   of 17 Floors          1
29th   of 39 Floors          1
13rd   of 26 Floors          1
14th   of 25 Floors          1
3rd   of 7 Floors            1
Ground of 22 Floors          1
13rd   of 34 Floors          1
23rd   of 36 Floors          1
Name: count, dtype: int64

In [31]:
# extract the flat number and number of floors in the building
df['floorNum'] = df['floorNum'].str.split(' ').str.get(0).replace('Ground','0').str.replace('Basement','-1').str.replace('Lower','0').str.extract(r'(\d+)')

## Facing

In [32]:
df['facing'].value_counts()

facing
North-East    505
East          490
North         301
South         203
West          183
North-West    162
South-East    144
South-West    135
Name: count, dtype: int64

In [33]:
print("null values : ",df['facing'].isnull().sum())

null values :  874

In [34]:
df['facing']=df['facing'].fillna('NA')

In [35]:
print(df['facing'].value_counts())

facing
NA            874
North-East    505
East          490
North         301
South         203
West          183
North-West    162
South-East    144
South-West    135
Name: count, dtype: int64

In [36]:
df.insert(loc=4,column='area',value=round((df['price']*10000000)/df['price_per_sqft']))
df.insert(loc=1,column='property_type',value='flat')

In [37]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,flat,maa bhagwati residency,0.45,5000.0,900.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,flat,apna enclave,0.50,7692.0,650.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,flat,tulsiani easy in homes,0.40,6722.0,595.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12,NA,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,flat,smart world orchard,1.47,12250.0,1200.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,NA,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,flat,parkwood westend,0.70,5204.0,1345.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,NA,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2997 entries, 0 to 3007
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    2997 non-null   object
 1   property_type    2997 non-null   object
 2   society          2997 non-null   object
 3   price            2996 non-null   float64
 4   price_per_sqft   2997 non-null   float64
 5   area             2996 non-null   float64
 6   areaWithType     2997 non-null   object
 7   bedRoom          2997 non-null   int64
 8   bathroom         2997 non-null   int64
 9   balcony          2997 non-null   object
 10  additionalRoom   2997 non-null   object
 11  address          2991 non-null   object
 12  floorNum         2995 non-null   object
 13  facing           2997 non-null   object
 14  agePossession    2996 non-null   object
 15  nearbyLocations  2906 non-null   object
 16  description      2997 non-null   object
 17  furnishDetails   2200 non-null   object
 18  features         2590 non-null   object
 19  rating           2668 non-null   object
dtypes: float64(3), int64(2), object(15)
memory usage: 491.7+ KB

In [39]:
df.to_csv('flats_cleaned.csv',index=False)
from google.colab import files
files.download('flats_cleaned.csv')